import { Space } from './types/game';

export const BOARD_SPACES: Omit<Space, 'boardSpaces'>[] = [
  {
    id: "start",
    type: "special",
    name: "START",
    position: "top-left",
    price: 0,
    ownedBy: null,
    rent: null,
    isMortgaged: false,
  },
  {
    id: "salvador",
    type: "city",
    name: "Salvador",
    position: "top",
    price: 60,
    country: "brazil",
    ownedBy: null,
    rent: 6,
    isMortgaged: false,
  },
  {
    id: "treasure1",
    type: "treasure",
    name: "Treasure",
    position: "top",
    price: 0,
    ownedBy: null,
    rent: null,
    isMortgaged: false,
  },
  {
    id: "rio",
    type: "city",
    name: "Rio",
    position: "top",
    price: 60,
    country: "brazil",
    ownedBy: null,
    rent: 6,
    isMortgaged: false,
  },
  {
    id: "income-tax",
    type: "tax",
    name: "Income Tax",
    position: "top",
    price: 200,
    ownedBy: null,
    rent: null,
    isMortgaged: false,
  },
  {
    id: "tlv-airport",
    type: "airport",
    name: "TLV Airport",
    position: "top",
    price: 200,
    ownedBy: null,
    rent: 25,
    isMortgaged: false,
  },
  {
    id: "tel-aviv",
    type: "city",
    name: "Tel Aviv",
    position: "top",
    price: 100,
    country: "israel",
    ownedBy: null,
    rent: 10,
    isMortgaged: false,
  },
  {
    id: "surprise1",
    type: "surprise",
    name: "Surprise",
    position: "top",
    price: 0,
    ownedBy: null,
    rent: null,
    isMortgaged: false,
  },
  {
    id: "haifa",
    type: "city",
    name: "Haifa",
    position: "top",
    price: 100,
    country: "israel",
    ownedBy: null,
    rent: 10,
    isMortgaged: false,
  },
  {
    id: "jerusalem",
    type: "city",
    name: "Jerusalem",
    position: "top",
    price: 120,
    country: "israel",
    ownedBy: null,
    rent: 12,
    isMortgaged: false,
  },
  {
    id: "prison",
    type: "special",
    name: "In Prison",
    position: "top-right",
    price: 0,
    ownedBy: null,
    rent: null,
    isMortgaged: false,
  },
  {
    id: "venice",
    type: "city",
    name: "Venice",
    position: "right",
    price: 140,
    country: "hungary",
    ownedBy: null,
    rent: 14,
    isMortgaged: false,
  },
  {
    id: "electric-company",
    type: "utility",
    name: "Electric Company",
    position: "right",
    price: 150,
    ownedBy: null,
    rent: 20,
    isMortgaged: false,
  },
  {
    id: "milan",
    type: "city",
    name: "Milan",
    position: "right",
    price: 140,
    country: "hungary",
    ownedBy: null,
    rent: 14,
    isMortgaged: false,
  },
  {
    id: "rome",
    type: "city",
    name: "Rome",
    position: "right",
    price: 160,
    country: "hungary",
    ownedBy: null,
    rent: 18,
    isMortgaged: false,
  },
  {
    id: "muc-airport",
    type: "airport",
    name: "MUC Airport",
    position: "right",
    price: 200,
    ownedBy: null,
    rent: 25,
    isMortgaged: false,
  },
  {
    id: "frankfurt",
    type: "city",
    name: "Frankfurt",
    position: "right",
    price: 180,
    country: "germany",
    ownedBy: null,
    rent: 20,
    isMortgaged: false,
  },
  {
    id: "treasure2",
    type: "treasure",
    name: "Treasure",
    position: "right",
    price: 0,
    ownedBy: null,
    rent: null,
    isMortgaged: false,
  },
  {
    id: "munich",
    type: "city",
    name: "Munich",
    position: "right",
    price: 180,
    country: "germany",
    ownedBy: null,
    rent: 22,
    isMortgaged: false,
  },
  {
    id: "berlin",
    type: "city",
    name: "Berlin",
    position: "right",
    price: 200,
    country: "germany",
    ownedBy: null,
    rent: 26,
    isMortgaged: false,
  },
  {
    id: "vacation",
    type: "special",
    name: "Vacation",
    position: "bottom-right",
    price: 0,
    ownedBy: null,
    rent: null,
    isMortgaged: false,
  },
  {
    id: "paris",
    type: "city",
    name: "Paris",
    position: "bottom",
    price: 220,
    country: "france",
    ownedBy: null,
    rent: 28,
    isMortgaged: false,
  },
  {
    id: "water-company",
    type: "utility",
    name: "Water Company",
    position: "bottom",
    price: 150,
    ownedBy: null,
    rent: 20,
    isMortgaged: false,
  },
  {
    id: "toulouse",
    type: "city",
    name: "Toulouse",
    position: "bottom",
    price: 220,
    country: "france",
    ownedBy: null,
    rent: 28,
    isMortgaged: false,
  },
  {
    id: "lyon",
    type: "city",
    name: "Lyon",
    position: "bottom",
    price: 240,
    country: "france",
    ownedBy: null,
    rent: 30,
    isMortgaged: false,
  },
  {
    id: "cdg-airport",
    type: "airport",
    name: "CDG Airport",
    position: "bottom",
    price: 200,
    ownedBy: null,
    rent: 25,
    isMortgaged: false,
  },
  {
    id: "shanghai",
    type: "city",
    name: "Shanghai",
    position: "bottom",
    price: 260,
    country: "china",
    ownedBy: null,
    rent: 32,
    isMortgaged: false,
  },
  {
    id: "beijing",
    type: "city",
    name: "Beijing",
    position: "bottom",
    price: 260,
    country: "china",
    ownedBy: null,
    rent: 34,
    isMortgaged: false,
  },
  {
    id: "surprise2",
    type: "surprise",
    name: "Surprise",
    position: "bottom",
    price: 0,
    ownedBy: null,
    rent: null,
    isMortgaged: false,
  },
  {
    id: "shenzhen",
    type: "city",
    name: "Shenzhen",
    position: "bottom",
    price: 280,
    country: "china",
    ownedBy: null,
    rent: 36,
    isMortgaged: false,
  },
  {
    id: "prison",
    type: "special",
    name: "Go to Prison",
    position: "bottom-left",
    price: 0,
    ownedBy: null,
    rent: null,
    isMortgaged: false,
  },
  {
    id: "london",
    type: "city",
    name: "London",
    position: "left",
    price: 300,
    country: "uk",
    ownedBy: null,
    rent: 38,
    isMortgaged: false,
  },
  {
    id: "treasure3",
    type: "treasure",
    name: "Treasure",
    position: "left",
    price: 0,
    ownedBy: null,
    rent: null,
    isMortgaged: false,
  },
  {
    id: "manchester",
    type: "city",
    name: "Manchester",
    position: "left",
    price: 300,
    country: "uk",
    ownedBy: null,
    rent: 40,
    isMortgaged: false,
  },
  {
    id: "liverpool",
    type: "city",
    name: "Liverpool",
    position: "left",
    price: 320,
    country: "uk",
    ownedBy: null,
    rent: 44,
    isMortgaged: false,
  },
  {
    id: "jfk-airport",
    type: "airport",
    name: "JFK Airport",
    position: "left",
    price: 200,
    ownedBy: null,
    rent: 25,
    isMortgaged: false,
  },
  {
    id: "san-francisco",
    type: "city",
    name: "San Francisco",
    position: "left",
    price: 350,
    country: "usa",
    ownedBy: null,
    rent: 50,
    isMortgaged: false,
  },
  {
    id: "surprise3",
    type: "surprise",
    name: "Surprise",
    position: "left",
    price: 0,
    ownedBy: null,
    rent: null,
    isMortgaged: false,
  },
  {
    id: "new-york",
    type: "city",
    name: "New York",
    position: "left",
    price: 400,
    country: "usa",
    ownedBy: null,
    rent: 100,
    isMortgaged: false,
  },
  {
    id: "luxury-tax",
    type: "tax",
    name: "Luxury Tax",
    position: "left",
    price: 100,
    ownedBy: null,
    rent: null,
    isMortgaged: false,
  },
];



export const surpriseCards:string[] = [
  "Advance to Start (Collect $200)",
  "Go to Jail",
  "Go back 3 spaces",
  "Bank pays you dividend of $50",
  "Pay tax of $45",
  "Take a trip to Rome",
  "Advance to New York",
  "Your building loan matures — collect $150",
  "Get out of Jail Free"
];
export const treasureCards:string[] = [
  "Bank error in your favor — collect $200",
  "Doctor's fees — Pay $50",
  "From sale of stock you get $50",
  "Get out of Jail Free",
  "Go to Jail",
  "Grand Opera Night — collect $50 from every player",
  "Holiday Fund matures — receive $100",
  "Income tax refund — collect $20",
  "Life insurance matures — collect $100",
  "Pay hospital fees of $100",
  "You inherit $100"
];